// src/vue3/DynamicParticles.vue
<template>
  <div :class="wrapperClass" :style="wrapperStyle">
    <vue-particles
      :id="canvasId"
      :options="particleOptions"
      @particles-loaded="onParticlesLoaded"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from "vue";
import type { Container } from "@tsparticles/engine";
import { buildDefaultParticleOptions } from "../shared/defaultOptions";
import type { Ref } from "vue";

const props = withDefaults(
  defineProps<{
    /** Vue ref used by DynamicSpeedMover (same as createDynamicParticlesState). */
    speedRef: Ref<number>;
    isPlayingRef: Ref<boolean>;
    particlesLinkRef: Ref<boolean>;
    /** Particle shape type (triangle, circle, square, …). */
    shape?: string;
    /** Deep-merge over default tsParticles options. */
    options?: Record<string, unknown>;
    canvasId?: string;
    wrapperClass?: string;
  }>(),
  {
    shape: "triangle",
    options: undefined,
    canvasId: "dynamic-tsparticles",
    wrapperClass: "dynamic-tsparticles-bg",
  }
);

const wrapperStyle = computed(() => ({
  width: "100%",
  height: "100%",
  position: "absolute" as const,
}));

let container: Container | null = null;

const particleOptions = ref(
  buildDefaultParticleOptions(props.speedRef.value, props.particlesLinkRef.value, props.options)
);

watch(
  () => props.shape,
  (type) => {
    if (!container?.options?.particles?.shape) return;
    container.options.particles.shape.type = type;
    container.refresh();
  }
);

watch(
  () => props.options,
  () => {
    particleOptions.value = buildDefaultParticleOptions(
      props.speedRef.value,
      props.particlesLinkRef.value,
      props.options
    );
    container?.refresh();
  },
  { deep: true }
);

function onParticlesLoaded(c: Container) {
  container = c;
}
</script>

// src/react/DynamicParticles.tsx
import Particles from "@tsparticles/react";
import { useCallback, useEffect, useRef, useState, type CSSProperties, type MutableRefObject } from "react";
import type { Container } from "@tsparticles/engine";
import { buildDefaultParticleOptions } from "../shared/defaultOptions";

export interface DynamicParticlesProps {
  speedRef: MutableRefObject<number>;
  isPlayingRef: MutableRefObject<boolean>;
  particlesLinkRef: MutableRefObject<boolean>;
  shape?: string;
  options?: Record<string, unknown>;
  id?: string;
  className?: string;
  style?: CSSProperties;
}

/**
 * React counterpart of the Vue `DynamicParticles` SFC: `Particles` from `@tsparticles/react` with the same default options + shape / overrides wiring.
 */
export function DynamicParticles({
  speedRef,
  isPlayingRef,
  particlesLinkRef,
  shape = "triangle",
  options,
  id = "dynamic-tsparticles",
  className,
  style,
}: DynamicParticlesProps) {
  const containerRef = useRef<Container | null>(null);
  const [particleOptions, setParticleOptions] = useState(() =>
    buildDefaultParticleOptions(
      speedRef.current,
      particlesLinkRef.current,
      options
    )
  );

  useEffect(() => {
    setParticleOptions(
      buildDefaultParticleOptions(
        speedRef.current,
        particlesLinkRef.current,
        options
      )
    );
  }, [options, speedRef, particlesLinkRef]);

  const onParticlesLoaded = useCallback(
    async (container?: Container) => {
      containerRef.current = container ?? null;
      const c = container ?? null;
      if (c?.options?.particles?.shape) {
        c.options.particles.shape.type = shape;
        c.refresh();
      }
    },
    [shape]
  );

  useEffect(() => {
    const c = containerRef.current;
    if (!c?.options?.particles?.shape) return;
    c.options.particles.shape.type = shape;
    c.refresh();
  }, [shape]);

  const wrapperClass = className ?? "dynamic-tsparticles-bg";

  return (
    <div
      className={wrapperClass}
      style={{
        position: "absolute",
        width: "100%",
        height: "100%",
        ...style,
      }}
    >
      <Particles
        id={id}
        options={particleOptions}
        particlesLoaded={onParticlesLoaded}
      />
    </div>
  );
}
