// examples/angular-minimal/src/app/app.component.ts
import { Component, OnDestroy, OnInit, inject, signal } from "@angular/core";
import { NgParticlesService } from "@tsparticles/angular";
import {
  AudioAnalyzer,
  createDynamicParticlesState,
  DynamicParticlesComponent,
} from "dynamic-tsparticles-angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [DynamicParticlesComponent],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
})
export class AppComponent implements OnInit, OnDestroy {
  private readonly ngParticles = inject(NgParticlesService);
  private readonly analyzer = AudioAnalyzer.getInstance();

  readonly state = createDynamicParticlesState({
    initialSpeed: 3,
    initialParticlesLink: true,
  });

  readonly shape = signal("circle");
  readonly linksUi = signal(true);
  readonly speedUi = signal(3);
  readonly audioUrl = signal<string | null>(null);

  readonly shapeOptions = [
    { value: "circle", label: "Circle" },
    { value: "square", label: "Square" },
    { value: "triangle", label: "Triangle" },
    { value: "star", label: "Star" },
    { value: "polygon", label: "Polygon" },
  ] as const;

  ngOnInit(): void {
    void this.ngParticles.init(this.state.initTsParticles);
  }

  ngOnDestroy(): void {
    this.analyzer.clearInterval();
    const u = this.audioUrl();
    if (u) {
      URL.revokeObjectURL(u);
    }
  }

  onSpeedInput(ev: Event): void {
    const n = Number((ev.target as HTMLInputElement).value);
    this.speedUi.set(n);
    this.state.speed.set(n);
  }

  onLinksChange(ev: Event): void {
    const v = (ev.target as HTMLInputElement).checked;
    this.linksUi.set(v);
    this.state.particlesLink.set(v);
  }

  onShapeChange(ev: Event): void {
    this.shape.set((ev.target as HTMLSelectElement).value);
  }

  onAudioFile(ev: Event): void {
    const input = ev.target as HTMLInputElement;
    const file = input.files?.[0];
    const prev = this.audioUrl();
    if (prev) {
      URL.revokeObjectURL(prev);
    }
    if (!file) {
      this.audioUrl.set(null);
      return;
    }
    this.audioUrl.set(URL.createObjectURL(file));
  }

  onAudioPlay(audioEl: HTMLAudioElement): void {
    if (!this.analyzer.isReady()) {
      this.analyzer.init(audioEl);
    }
    void this.analyzer.audioContext?.resume();
    this.analyzer.clearInterval();
    this.state.isPlaying.set(true);
    this.analyzer.setInterval(() => {
      const next = this.analyzer.getNewAudioSpeed(this.state.speed());
      this.state.speed.set(next);
      this.speedUi.set(next);
    });
  }

  onAudioStop(): void {
    this.analyzer.clearInterval();
    this.state.isPlaying.set(false);
  }
}

<div class="layout">
  <div class="particles-wrap">
    <dynamic-particles
      [speed]="state.speed"
      [isPlaying]="state.isPlaying"
      [particlesLink]="state.particlesLink"
      [shape]="shape()">
    </dynamic-particles>
  </div>
  <div class="controls">
    <label>
      Speed: {{ speedUi() }}
      <input
        type="range"
        min="0"
        max="20"
        [value]="speedUi()"
        (input)="onSpeedInput($event)" />
    </label>
    <label class="row">
      <input
        type="checkbox"
        [checked]="linksUi()"
        (change)="onLinksChange($event)" />
      Links
    </label>
    <label>
      Shape
      <select class="shape-select" (change)="onShapeChange($event)">
        @for (opt of shapeOptions; track opt.value) {
          <option [value]="opt.value" [selected]="opt.value === shape()">
            {{ opt.label }}
          </option>
        }
      </select>
    </label>
    <div class="audio-block">
      <span class="audio-label">Audio track (optional)</span>
      <input
        class="file-input"
        type="file"
        accept="audio/*"
        (change)="onAudioFile($event)" />
      @if (audioUrl(); as url) {
        <audio
          #audioRef
          class="audio-el"
          [src]="url"
          controls
          (play)="onAudioPlay(audioRef)"
          (pause)="onAudioStop()"
          (ended)="onAudioStop()">
        </audio>
      } @else {
        <p class="audio-hint">
          Choose a file, then press play — particle speed follows the beat.
        </p>
      }
    </div>
  </div>
</div>

// examples/react-minimal/src/App.tsx
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { initParticlesEngine } from "@tsparticles/react";
import {
  AudioAnalyzer,
  DynamicParticles,
  useDynamicParticlesState,
} from "dynamic-tsparticles-react";

const SHAPE_OPTIONS = [
  { value: "circle", label: "Circle" },
  { value: "square", label: "Square" },
  { value: "triangle", label: "Triangle" },
  { value: "star", label: "Star" },
  { value: "polygon", label: "Polygon" },
] as const;

export default function App() {
  const [engineReady, setEngineReady] = useState(false);
  const state = useDynamicParticlesState({
    initialSpeed: 3,
    initialParticlesLink: true,
  });

  const [speedUi, setSpeedUi] = useState(3);
  const [shape, setShape] = useState("circle");
  const [linksUi, setLinksUi] = useState(true);

  useEffect(() => {
    void initParticlesEngine(state.initTsParticles).then(() => setEngineReady(true));
  }, [state.initTsParticles]);

  useEffect(() => {
    state.speedRef.current = speedUi;
  }, [speedUi, state.speedRef]);

  useEffect(() => {
    state.particlesLinkRef.current = linksUi;
  }, [linksUi, state.particlesLinkRef]);

  const audioRef = useRef<HTMLAudioElement>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const analyzer = AudioAnalyzer.getInstance();

  const onAudioFile = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (audioUrl) {
      URL.revokeObjectURL(audioUrl);
      setAudioUrl(null);
    }
    if (!file) return;
    setAudioUrl(URL.createObjectURL(file));
  };

  const onAudioPlay = () => {
    const el = audioRef.current;
    if (!el) return;
    if (!analyzer.isReady()) {
      analyzer.init(el);
    }
    void analyzer.audioContext?.resume();
    analyzer.clearInterval();
    state.isPlayingRef.current = true;
    analyzer.setInterval(() => {
      const next = analyzer.getNewAudioSpeed(state.speedRef.current);
      state.speedRef.current = next;
      setSpeedUi(next);
    });
  };

  const onAudioStop = () => {
    analyzer.clearInterval();
    state.isPlayingRef.current = false;
  };

  useEffect(() => {
    return () => {
      analyzer.clearInterval();
      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
      }
    };
  }, [audioUrl]);

  return (
    <div className="layout">
      <div className="particles-wrap">
        {engineReady ? (
          <DynamicParticles
            speedRef={state.speedRef}
            isPlayingRef={state.isPlayingRef}
            particlesLinkRef={state.particlesLinkRef}
            shape={shape}
          />
        ) : null}
      </div>
      <div className="controls">
        <label>
          Speed: {speedUi}
          <input
            type="range"
            min={0}
            max={20}
            value={speedUi}
            onChange={(e) => {
              const n = Number(e.target.value);
              setSpeedUi(n);
              state.speedRef.current = n;
            }}
          />
        </label>
        <label className="row">
          <input
            type="checkbox"
            checked={linksUi}
            onChange={(e) => {
              const v = e.target.checked;
              setLinksUi(v);
              state.particlesLinkRef.current = v;
            }}
          />
          Links
        </label>
        <label>
          Shape
          <select
            className="shape-select"
            value={shape}
            onChange={(e) => setShape(e.target.value)}
          >
            {SHAPE_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        </label>
        <div className="audio-block">
          <span className="audio-label">Audio track (optional)</span>
          <input
            className="file-input"
            type="file"
            accept="audio/*"
            onChange={onAudioFile}
          />
          {audioUrl ? (
            <audio
              ref={audioRef}
              className="audio-el"
              src={audioUrl}
              controls
              onPlay={onAudioPlay}
              onPause={onAudioStop}
              onEnded={onAudioStop}
            />
          ) : (
            <p className="audio-hint">
              Choose a file, then press play — particle speed follows the beat.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
